# answer (1i)
def circle_area():
    radius = float(input("Enter the radius of the sphere"))
    import math
    pie = math.pi
    radius=float(input("the parameter of the circle"))
    circle_area =pie*radius^2
    print(f"The area of the circle with pie{3.14}is{circle_area}")
    
# (ii)
list=[4,7,2,9,12,15]
sum=()
all_odd_numbers=[7,9,15]
print(f"(sum of all odd numbers)")

#(v)
student_info={'name':'Alice','age':20,'grade':'A'}
student_info['age']='20'
print(student_info)
#creating a list
student_info['name':'Alice','age':20,'grade':'A','City':'Kampala']
student_info.insert[3,'City':'Kampala']
print(("student_info.insert(3,'City':'Kampala'"))

